version: '3.9'

services:
  caddy:
    image: caddy:2.5.1
    container_name: caddy_webapp
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - './.docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
      - ./public:/srv/app/public

  php:
    build:
      context: ./.docker/php
    restart: unless-stopped
    container_name: php_webapp
    volumes:
      - ./:/srv/app

networks:
  default:
    name: network_webapp
