version: '3.9'

services:
  caddy:
    image: caddy:2.5.1
    container_name: caddy_webapp
    restart: unless-stopped
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost:80}
    ports:
      - "${CADDY_PORT:-8080}:80"
      #- "${CADDY_HTTPS_PORT:-8443}:443"
    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
      - ./../public:/srv/app/public

  php:
    build:
      context: ./php
    restart: unless-stopped
    container_name: php_webapp
    volumes:
      - ./..:/srv/app

networks:
  default:
    name: network_webapp
